# 端口号配置
server:
  port: 8089

# 数据库连接配置
spring:
  datasource:
    # 使用阿里的druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1412

  # MP 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 驼峰下划线转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_empty   # 配置MP在更新时只更新非空和非NULL的字段
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1        # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0    # 逻辑未删除值(默认为 0)

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.xg.web.sys_role.controller,top.xg.web.sys_user.controller,top.xg.web.sys_menu.controller

  # knife4j
  knife4j:
    enable: true
    setting:
      language: zh_cn
    basic:
      enable: true
      username: admin
      password: 123456
