aliyun-oss.endpoint=https://oss-cn-hangzhou.aliyuncs.com
aliyun-oss.bucket=yian2909-bucket
aliyun-oss.dir=images/
aliyun-oss.host=https://yian2909-bucket.oss-cn-hangzhou.aliyuncs.com
aliyun-oss.ak=LTAI5tMUpntrGxqt6ZLrCw5s
aliyun-oss.secret=hXbObSeZpDyQYFAYBC34UwIILQOQpX